version: '3.8'

services:
  personal-website:
    build: .
    container_name: personal-website-prod
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.personal-website-prod.rule=Host(`indraswara.me`)"
      - "traefik.http.routers.personal-website-prod.entrypoints=websecure"
      - "traefik.http.routers.personal-website-prod.tls.certresolver=letsencrypt"
      - "traefik.http.routers.personal-website-prod.tls=true"
      - "traefik.http.services.personal-website-prod.loadbalancer.server.port=80"
      - "traefik.http.routers.personal-website-redirect.rule=Host(`indraswara.me`)"
      - "traefik.http.routers.personal-website-redirect.entrypoints=web"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.personal-website-redirect.middlewares=redirect-to-https@docker"
    networks:
      - traefik_default
    restart: unless-stopped

networks:
  traefik_default:
    external: true
